services:
  - type: web
    name: planner-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: ALENA_USER_ID
        sync: false
      - key: OLEG_USER_ID
        sync: false
    pythonVersion: "3.12.9"
